// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package simple

import (
	"github.com/google/wire"
	"io"
	"os"
)

// Injectors from injector.go:

func InitializeService(isError bool) (*SimpleService, error) {
	simpleRepository := NewSimpleRepository(isError)
	simpleService, err := NewSimpleService(simpleRepository)
	if err != nil {
		return nil, err
	}
	return simpleService, nil
}

func InitializeDatabaseRepository() *DatabaseRepository {
	databasePostgreSQL := NewDatabasePostgreSQL()
	databaseMongoDB := NewDatabaseMongoDB()
	databaseRepository := NewDatabaseRepository(databasePostgreSQL, databaseMongoDB)
	return databaseRepository
}

func InitializeFooBarService() *FooBarService {
	fooRepository := NewFooRepository()
	fooService := NewFooService(fooRepository)
	barRepository := NewBarRepository()
	barService := NewBarService(barRepository)
	fooBarService := NewFooBarService(fooService, barService)
	return fooBarService
}

func InitialieHelloService() *HelloService {
	sayHelloImpl := NewSayHelloImpl()
	helloService := NewHelloService(sayHelloImpl)
	return helloService
}

// Struct Provider
// ===== STRUCT PROVIDER =====
func InitializedFooBarStruct() *FooBarStruct {
	foo := NewFoo()
	bar := NewBar()
	fooBarStruct := &FooBarStruct{
		Foo: foo,
		Bar: bar,
	}
	return fooBarStruct
}

func InitializeFooBarUsingVariable() *FooBarStruct {
	foo := _wireFooValue
	bar := _wireBarValue
	fooBarStruct := &FooBarStruct{
		Foo: foo,
		Bar: bar,
	}
	return fooBarStruct
}

var (
	_wireFooValue = &Foo{}
	_wireBarValue = &Bar{}
)

// Interface Value
func InitializedReader() io.Reader {
	reader := _wireFileValue
	return reader
}

var (
	_wireFileValue = os.Stdin
)

// Struct Field Provider
func InitializedConfiguration() *Configuration {
	application := NewApplication()
	configuration := application.Configuration
	return configuration
}

// Clean Up Function
func InitializedConnection(name string) (*Connection, func()) {
	file, cleanup := NewFile(name)
	connection, cleanup2 := NewConnection(file)
	return connection, func() {
		cleanup2()
		cleanup()
	}
}

// injector.go:

// Provider Set
// Hanya Groping antar Provider
var fooSet = wire.NewSet(NewFooRepository, NewFooService)

var barSet = wire.NewSet(NewBarRepository, NewBarService)

// Binding Interface
var helloSet = wire.NewSet(
	NewSayHelloImpl, wire.Bind(new(SayHello), new(*SayHelloImpl)),
)

// Binding Values
var fooBarValueSet = wire.NewSet(wire.Value(&Foo{}), wire.Value(&Bar{}))
